---

- git_config:
    name: alias.co
    scope: global
    value: checkout

- git_config:
    name: alias.st
    scope: global
    value: status

- git_config:
    name: user.email
    scope: global
    value: "{{ git.mail }}"

- git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"