---

- git_config:
    name: alias.co
    scope: global
    value: checkout

- git_config:
    name: alias.st
    scope: global
    value: status


- git_config:
    name: user.email
    repo: "~/projects"
    scope: global
    value: 'c@c.de'